@NET_API_HostAddress = http://localhost:5018
@Token = Test

GET {{NET_API_HostAddress}}/Item/List
Accept: application/json
Authorization: {{Token}}
###

POST {{NET_API_HostAddress}}/Auth/Login 
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
