@NET_API_HostAddress = http://localhost:5018
@Token = 0CF2892640A8675272ABC992B2C367D67438EFCE3FD5D3FF063ED777BD247BD5

GET {{NET_API_HostAddress}}/Item/List
Accept: application/json
Authorization: {{Token}}
###

POST {{NET_API_HostAddress}}/Auth/Login 
Accept: application/json
Content-Type: application/json

{
  "username": "user1",
  "password": "password1"
}

###
